[package]
name = "resourcespace-client"
edition = "2024"
version = "0.1.0"
authors = ["Connor Kooistra"]
description = "A Rust client for the communicating with ResourceSpace API"
license = "MIT OR Apache-2.0"
repository = "https://github.com/cdkooistra/resourcespace-client"
keywords = ["resourcespace", "api", "client"]
categories = ["api-bindings"]

[dependencies]
reqwest = { version = "0.13", features = ["form", "json", "multipart", "stream"] }
sha2 = "0.10"
hex = "0.4"
tokio = { version = "1", features = ["full"] }
serde_json = "1.0.149"
serde = { version = "1.0.228", features = ["derive"] }
serde_qs = "1.1.1"
thiserror = "2.0.18"
dotenvy = "0.15"
url = "2.5.8"
validator = { version = "0.20.0", features = ["derive"] }
secrecy = "0.10.3"
