[package]
name = "resourcespace-client"
version = "0.1.0"
authors = ["Connor Kooistra"]
description = "A Rust client for the communicating with ResourceSpace API"
license = "MIT OR Apache-2.0"
repository = "https://github.com/cdkooistra/resourcespace-client"
keywords = ["resourcespace", "api", "client"]
categories = ["api-bindings"]
